### Create a new product
POST http://localhost:3000/api/product
content-type: application/json

{
    "name": "water",
    "price": 1.99,
    "description": "A water."
}

### Get all products
GET http://localhost:3000/api/product

### Get a product by its id
GET http://localhost:3000/api/product/6307713117678597eafbb2b8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjMwYTI3ZTNkYjg4MDM5YzJlZTNkOTBlIiwibmFtZSI6IlRlc3QyIiwiZW1haWwiOiJUZXN0MkB0ZXN0LmNvbSJ9LCJpYXQiOjE2NjE2MTAwMjQsImV4cCI6MTY2MTYxMzYyNH0.8bFTnLkDAzEctVuNDcRbhTmVL5m8TLHP21YvmRe3PEM

### Update a product
PATCH http://localhost:3000/api/product/6307713117678597eafbb2b8
content-type: application/json

{
    "price": 2.99
}

### Register a new user
POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "name": "Test2",
    "email": "Test2@test.com",
    "password": "Test"
}

### Login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "Test2@test.com",
    "password": "Test"
}