### Create a new product
POST http://localhost:3000/api/product
content-type: application/json

{
    "name": "chocolate",
    "price": 5.99
}

### Get all products
GET http://localhost:3000/api/product

### Get a product by its id
GET http://localhost:3000/api/product/6307713117678597eafbb2b8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjMwYjVlMTc1MTQ3ZTNkMWU2YWY1NTM4IiwibmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20ifSwiaWF0IjoxNjYxNjg5NTAzLCJleHAiOjE2NjE2OTMxMDN9.FBM9GneYifPxjCY_DVoX2TCuIiN82bWV0OqzFi_wVao

### Update a product
PATCH http://localhost:3000/api/product/6307713117678597eafbb2b8
content-type: application/json

{
    "price": 2.99
}

### Register a new user
POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "name": "Admin",
    "email": "admin@admin.com",
    "password": "admin"
}

### Login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

### Verify JWT
POST http://localhost:3000/api/auth/verify-jwt
content-type: application/json

{
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjMwYjVlMTc1MTQ3ZTNkMWU2YWY1NTM4IiwibmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20ifSwiaWF0IjoxNjYxNjg5NTAzLCJleHAiOjE2NjE2OTMxMDN9.FBM9GneYifPxjCY_DVoX2TCuIiN82bWV0OqzFi_wVao"
}

### Stripe payment
POST http://localhost:3000/api/stripe
content-type: application/json

{
    "cart": [
        {
            "description": "Learning react",
            "name": "React course",
            "price": 9.99,
            "quantity": 2,
            "__v": 0,
            "_id": "6307713117678597eafbb2b2"
        }
    ]
}